import type { PackageValidationSchemaType } from '../schema/PackageSchema';

export const initialPackageValues: PackageValidationSchemaType = {
  country_id: '',
  city_id: [],
  package_type_id: '',
  category_id: '',
  name: '',
  description: '',
  destination: '',
  duration: 0,
  start_point: '',
  end_point: '',
  group_size: '',
  max_altitude: '',
  previous_price: '',
  current_price: '',
  start_date: '',
  end_date: '',
  cancellation_policy: '',
  payment_policy: '',
  terms_conditions: '',
  is_top_tour: false,
  is_top_deals: false,
  image: undefined,
  availability_month: [],
  inclusions: [{ title: '', description: '' }],
  exclusions: [{ title: '', description: '' }],
  notices: [{ title: '', description: '' }],
  highlights: [{ title: '', description: '' }],
  itinerary: [{ day: 0, title: '', description: '' }],
  meals: [{ title: '', description: '' }],
  accommodations: [{ title: '', description: '' }],
  activities: [{ title: '', description: '' }],
};
